server:
  port: 9093

spring:
  application:
    name: ms-store
  cloud:
    config:
      enabled: false          # NO usar Config Server en local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecm   # <--- usa la DB que sí existe en el contenedor
    username: user1234                            # <--- igual al POSTGRES_USER
    password: passwduser1234                      # <--- igual al POSTGRES_PASSWORD
 
application:
  microservice:
    ms-user: http://localhost:9090
    ms-media: http://localhost:9094

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,r2dbc
        liveness:
          include: livenessState
