apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:16.7
          name: postgres
          ports:
            - containerPort: {{ .Values.dbPort }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: dbName
                  name: app-config-db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: dbUser
                  name: app-config-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: postgres-secret
