apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          ports:
            - containerPort: {{ .Values.dbPort }}
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: dbName
                  name: app-config-db
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: dbUser
                  name: app-config-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: postgres-secret
          volumeMounts:
            - mountPath: {{ .Values.volumePath }}
              name: {{ .Values.volumeName }}
      volumes:
        - name: {{ .Values.volumeName }}
          persistentVolumeClaim:
            claimName: postgres-pvc