apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: postgres
spec:
  ports:
    - port: {{ .Values.dbPort }}
      protocol: TCP
      targetPort: {{ .Values.dbPort }}
  selector:
    app: postgres
  type: ClusterIP