apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-configmap
data:
  springProfile: {{ .Values.springProfile | quote }}
  dbUser: {{ .Values.dbUser | quote }}
  dbName: {{ .Values.dbName | quote }}