apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.microservicesPort }}
      protocol: TCP
      targetPort: {{ .Values.microservicesPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.microservicesServiceType }}