spring:
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: r2dbc:postgresql://${DB_HOST}:5432/ecm

  liquibase:
    url: jdbc:postgresql://${DB_HOST}:5432/ecm
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

springdoc:
  swagger-ui:
    path: /bcn/api/openapi/ui/swagger-ui.html
  api-docs:
    path: /bcn/api/openapi/docs/api-docs.yaml

application:
  microservice:
    url:
      ms-user: ${MS_USER}
      ms-location: ${MS_LOCATION}
      ms-store: ${MS_STORE}