spring:
  r2dbc:
    username: admin
    password: change_me
    url: r2dbc:postgresql://postgres:5432/ecm

  liquibase:
    url: jdbc:postgresql://postgres:5432/ecm
    user: admin
    password: change_me
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

springdoc:
  swagger-ui:
    path: /bcn/api/openapi/ui/swagger-ui.html
  api-docs:
    path: /bcn/api/openapi/docs/api-docs.yaml

application:
  microservice:
    url:
      ms-user: http://ms-user:9090
      ms-location: http://ms-location:9092/bcn/api/location
      ms-store: http://ms-store:9093