spring:
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: r2dbc:postgresql://bcn-database.czuieagmspgl.us-east-2.rds.amazonaws.com:5432/bacan
    properties:
      sslMode: DISABLE # Update rds.force_ssl to 0

  liquibase:
    url: jdbc:postgresql://bcn-database.czuieagmspgl.us-east-2.rds.amazonaws.com:5432/bacan
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

springdoc:
  swagger-ui:
    path: /bcn/api/openapi/ui/swagger-ui.html
  api-docs:
    path: /bcn/api/openapi/docs/api-docs.yaml

application:
  microservice:
    url:
      ms-user: http://ms-user:9090
      ms-location: http://ms-location:9092
      ms-store: http://ms-store:9093