spring:
  r2dbc:
    username: admin
    password: change_me
    url: r2dbc:postgresql://localhost:5432/ecm

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG