spring:
  r2dbc:
    username: admin
    password: change_me
    url: r2dbc:postgresql://postgres:5432/ecm

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

springdoc:
  swagger-ui:
    path: /bcn/api/openapi/ui/swagger-ui.html
  api-docs:
    path: /bcn/api/openapi/docs/api-docs.yaml

application:
  upload:
    path: /home/cw-lambda/Workspace/bacan-backend/upload
  microservice:
    ms-user: http://ms-user:9090
    ms-role: http://ms-role:9091
    ms-location: http://ms-location:9092
    ms-store: http://ms-store:9093
    ms-media: http://ms-media:9094