server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecm?sslMode=disable
    username: admin
    password: admin123

application:
  microservice:
    ms-user: http://127.0.0.1:9090
    ms-role: http://127.0.0.1:9091
    ms-location: http://127.0.0.1:9092
    ms-store: http://127.0.0.1:8082
    ms-media: http://127.0.0.1:9094

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,refresh
  endpoint:
    env:
      enabled: true
      show-values: ALWAYS   # ¡Ojo! Muestra valores tal cual (solo en local)

logging:
  level:
    io.r2dbc.postgresql: DEBUG
    org.springframework.r2dbc: DEBUG
