server:
  port: 8991

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-user
              uri: http://localhost:9090
              predicates:
                - Path=/bcn/api/user/**
            - id: ms-role
              uri: http://localhost:9091
              predicates:
                - Path=/bcn/api/role/**
            - id: ms-location
              uri: http://localhost:9092
              predicates:
                - Path=/bcn/api/location/**
            - id: ms-store
              uri: http://localhost:9093
              predicates:
                - Path=/bcn/api/store/**, /bcn/api/category/**, /bcn/api/product/**
            - id: ms-media
              uri: http://localhost:9094
              predicates:
                - Path=/bcn/api/media/**
            - id: ms-payment
              uri: http://localhost:9095
              predicates:
                - Path=/bcn/api/payment/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://127.0.0.1:5173"
                  - "http://localhost:5173"
                allowedMethods: "*"
                allowedHeaders: "*"
                allow-credentials: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.sa-east-1.amazonaws.com/sa-east-1_159w2HKSs