server:
  port: 8991

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-user
              uri: http://ms-user:9090
              predicates:
                - Path=/bcn/api/user/**
            - id: ms-location
              uri: http://ms-location:9092
              predicates:
                - Path=/bcn/api/location/**
            - id: ms-store
              uri: http://ms-store:9093
              predicates:
                - Path=/bcn/api/store/**, /bcn/api/category/**, /bcn/api/product/**
            - id: ms-payment
              uri: http://ms-payment:9095
              predicates:
                - Path=/bcn/api/payment/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://127.0.0.1:5173"
                  - "http://localhost:5173"
                allowedMethods: "*"
                allowedHeaders: "*"
                allow-credentials: true
